//first, we will import all the library and modules which are required in this project.
//Express will help us to create a server on which our web application will run.
//Multer will help in uploading the file on our web page and storing it in our database.
//Unirest will be used to make API requests from our server.
const express = require('express')
const app = express()
const ejs = require('ejs')
const multer = require('multer')
const fs = require('fs')
var unirest = require("unirest");

var req = unirest("GET", "https://edamam-food-and-grocery-database.p.rapidapi.com/parser");
var link
let temp
var k = 0
//Further, we will import that library which will help us in performing Optical Character Recognition
const {TesseractWorker} = require('tesseract.js')
const worker = new TesseractWorker();
// Setting up the port value
const port = 3000

//setting up view engine
app.set('view engine','ejs')

//static path for css
app.use(express.static('views'))

//multer for uploading files
// Following code is for uploading file on our web page using Multer.
//We will be defining destination and filename of the uploaded file.
//Each of the mentioned things takes three parameteres i.e. "request", "file" and a "call back" function
const storage = multer.diskStorage({
    destination: (req,file,cb) => {
        cb(null,'./uploads')
    },
    filename: (req,file,cb) => {
        cb(null,file.originalname)
    }
})
 const upload = multer({
     storage: storage
 }).single("uploaded")

 //routing-GET
 //The following code will render index.ejs as a response when '/' is requested by the user. In case of any error, "err" gets called.
app.get('/',(req,res,err)=>{
    if(err){
        console.log(err)
    }
    res.render('index.ejs')
})
//console.log('pls work!') isko report mein mat likhna

//routing-POST
//The following code will help us to make POST request when "/details" is requsted by the user.
app.post('/details',(req,res,err)=>{
  upload(req,res,err => {
      fs.readFile(`./uploads/${req.file.originalname}` , (err,data) => {
          if(err) return console.log("error is",err);
        // Folllowing is the worker object which was created above while importing Tesseract
          worker
           .recognize(data,"eng", {tess_js_pdf: "1"})
          //This will print the progress of the OCR in the console so that we can know how much of OCR has been done successfully
          .progress(progress => {
              console.log(progress)
          })
            //result.txt contains the text which is extracted by us with the help of Optical Character Recogniton.
            //To get the accurate result, we will have to process the data which has been extracted. With the help
          // of split function, we will seprate the extracted text from empty spaces and newlines. The result obtained from the 
          // previous operation is stored in a new arr called "newArr". The new array obtained is not flat, so to make the array
        // flat, we will use the spread (...) operator.
          .then(result => {
               var word = result.text;
               var arr = word.split("\n");
                var newArr = []

               for(var i = 0; i<arr.length; i++){
                   var character = arr[i].split(" ")
                   newArr.push(character)
               }

            finalArr = [].concat(...newArr);
            console.log(finalArr)
            temp = finalArr[0]
            //console.log(typeof(temp)) dont write in report
            //res.redirect(link) // dont write in report
              //This second .then function will help us to redirect to the link generated by the API call.
          }).then(temp=>{
            //console.log(finalArr[0])
            param = finalArr[0]
            api(param)
            // res.redirect(link)
            function red(){
                res.redirect(link)
            }
            setTimeout(red,3000)
            
          })
          //.finally(() => worker.terminate())
          
      })
  })

})

//This is the most important fucntion as it is reponsible for making API calls based on the text extracted from the food label
// It takes one parameter which is nothing but the text given by worker object by the first .then method.

 function api(param){
                var i = "lays"
                req.query({
                    "ingr": `${param}`
                });
                
                req.headers({
                    "x-rapidapi-host": "edamam-food-and-grocery-database.p.rapidapi.com",
                    "x-rapidapi-key": "201594df46msh2bd5bd39dfa30f1p1d18c9jsn57e1cbc0afc3"
                });
                
                
                req.end(function (res) {
                    if (res.error) throw new Error(res.error);
                
                    link = (res.body._links.next.href);
                    console.log(link)
                });
                
            }


//SETTING UP SERVER
app.listen(port);
